### ISSUE TITLE
Hello... A tad of an issue.

### ISSUE THREAD

**Issue by rjstechnet** [MTSGJ/helper_scripts#1]
[Wed Jan 24 14:36:10.829448 2024] [proxy_fcgi:error] [pid 9381] [client 127.0.0.1:60498] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND (name LIKE '%Var%' OR description LIKE '%Var%')  LIMIT 0,101' at line 1 in /var/www/html/public_html/services/opensim.phplib/mysql.func.php:118\nStack trace:\n#0 /var/www/html/public_html/services/opensim.phplib/mysql.func.php(118): mysqli_query()\n#1 /var/www/html/public_html/services/helper/query.php(430): DB->query()\n#2 [internal function]: dir_classified_query()\n#3 /var/www/html/public_html/services/helper/query.php(590): xmlrpc_server_call_method()\n#4 {main}\n  thrown in /var/www/html/public_html/services/opensim.phplib/mysql.func.php on line 118'

0.9.0.3 trunk on both. Using updates, but problem with OpenSimSearch. Latter PHP installed. Most all works, this doesn't on this end.

Thank you!

**Comment by rjstechnet** [comment]
Also you have in /opensim.modules/Profile/conf/OpenSim.ini.example

--
;Add the following to your own OpenSim.ini file to make the UserProfile service working

[Profile]
    Module = "OpenSimProfileModule"

    ; Change it to your own HTTP server to have the Profile server work
    ProfileURI = "YOUR_HELPER_URL/profile.php"
--

Couldn't get it to work, but change "ProfileURI" to "ProfileURL" and it works.

Thank you!

**Comment by rjstechnet** [comment]
Also, even with issues, thank you for continuing the work on the helper scripts and modules.
